# Generated by Django 4.1.5 on 2023-11-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_termino', models.DateTimeField()),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
    ]
