# Generated by Django 4.1.5 on 2023-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='segmento',
            field=models.CharField(choices=[('Co', 'Comunidad usm'), ('Es', 'Estudiante'), ('Pr', 'Profesor'), ('Je', 'Jefe de Carrera')], default='Co', max_length=50),
        ),
        migrations.AlterField(
            model_name='hito',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hito',
            name='tipo',
            field=models.CharField(blank=True, choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('SA', 'Suspension de Actividades'), ('SaPM', 'Suspension de Actividades PM'), ('P', 'Periodo Lectivo'), ('S', 'Suspension de Actividades'), ('C', 'Ceremonia'), ('Ed', 'EDDA'), ('E', 'Evaluacion'), ('A', 'Ayudantias'), ('H', 'Hito Academico'), ('Se', 'Secretaria Academica'), ('O', 'OAI')], max_length=50, null=True),
        ),
    ]
