# Generated by Django 4.1.5 on 2023-11-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_hito_segmento_alter_hito_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hito',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
