# Generated by Django 4.1.5 on 2023-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_hito_fecha_inicio_alter_hito_fecha_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hito',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hito',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
