# Generated by Django 4.2 on 2023-11-28 11:47

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0006_alter_hito_fecha_inicio_alter_hito_fecha_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Co', 'Comunidad usm'), ('Es', 'Estudiante'), ('Pr', 'Profesor'), ('Je', 'Jefe de Carrera'), ('De', 'Developer')], default='Co', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': [builtins.id],
            },
        ),
    ]
