# Generated by Django 4.2 on 2023-11-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_userrol_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrol',
            options={'ordering': ['id'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
